require 'rspec/core'
require 'active_support/core_ext/array/extract_options'
require 'active_support/core_ext/hash/slice'
require 'active_support/core_ext/object/try'

require 'remockable/active_model/helpers'
require 'remockable/active_model/validate_acceptance_of'
require 'remockable/active_model/validate_confirmation_of'
require 'remockable/active_model/validate_exclusion_of'
require 'remockable/active_model/validate_format_of'
require 'remockable/active_model/validate_inclusion_of'
require 'remockable/active_model/validate_length_of'
require 'remockable/active_model/validate_numericality_of'
require 'remockable/active_model/validate_presence_of'
