require 'rspec/core'
require 'active_support/core_ext/array/extract_options'
require 'active_support/core_ext/hash/slice'
require 'active_support/core_ext/object/try'

require 'remockable/matchers/validate_acceptance_of'
require 'remockable/matchers/validate_confirmation_of'
require 'remockable/matchers/validate_exclusion_of'
require 'remockable/matchers/validate_format_of'
require 'remockable/matchers/validate_inclusion_of'
require 'remockable/matchers/validate_length_of'
require 'remockable/matchers/validate_numericality_of'
require 'remockable/matchers/validate_presence_of'
