name: Build
on:
  - push
  - pull_request

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    if: github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository
    strategy:
      fail-fast: false
      matrix:
        ruby:
          - "2.5"
          - "2.6"
          - "2.7"
          - "3.0"
          - "3.1"
        rails:
          - "4.2"
          - "5.0"
          - "5.1"
          - "5.2"
          - "6.0"
          - "6.1"
        exclude:
          - ruby: "2.7"
            rails: "4.2"

          - ruby: "3.0"
            rails: "4.2"
          - ruby: "3.0"
            rails: "5.0"
          - ruby: "3.0"
            rails: "5.1"
          - ruby: "3.0"
            rails: "5.2"

          - ruby: "3.1"
            rails: "4.2"
          - ruby: "3.1"
            rails: "5.0"
          - ruby: "3.1"
            rails: "5.1"
          - ruby: "3.1"
            rails: "5.2"
          - ruby: "3.1"
            rails: "6.0"

    runs-on: "ubuntu-latest"

    env:
      BUNDLE_GEMFILE: gemfiles/rails_${{ matrix.rails }}.gemfile
      RUBYOPT: "--disable-error_highlight"

    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Setup project
        run: bundle install
      - name: Run tests
        run: bundle exec rspec
